name: create

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - name: Download Ngrok & NSSM
      run: |
        Invoke-WebRequest https://raw.githubusercontent.com/putrajo/bejoer/main/.github/workflows/ngrok.zip -OutFile ngrok.zip
        Invoke-WebRequest https://raw.githubusercontent.com/putrajo/bejoer/main/.github/workflows/nssm.exe -OutFile nssm.exe
    - name: Copy NSSM to Windows Directory.
      run: copy nssm.exe C:\Windows\System32
    - name: Extracting Ngrok.
      run: Expand-Archive ngrok.zip
    - name: Copy Ngrok to Windows Directory.
      run: copy ngrok.exe C:\Windows\System32
    - name: Connect your NGROK account
      run: .\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Download Important Files.
      run: |
        Invoke-WebRequest https://raw.githubusercontent.com/putrajo/bejoer/main/.github/workflows/NGROK-AP.bat -OutFile NGROK-AP.bat
        Invoke-WebRequest https://raw.githubusercontent.com/putrajo/bejoer/main/.github/workflows/NGROK-CHECK.bat -OutFile NGROK-CHECK.bat
        Invoke-WebRequest https://raw.githubusercontent.com/putrajo/bejoer/main/.github/workflows/loop.bat -OutFile loop.bat
    - name: Make YML file for NGROK.
      run: start NGROK-AP.bat
    - name: Enable RDP Access.
      run: | 
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - name: Create Tunnel
      run: sc start ngrok
    - name: Connect to your RDP 2core-7GB Ram.
      run: cmd /c NGROK-CHECK.bat
    - name: All Done!!
      run: cmd /c loop.bat 
